interval: 5m

servers:
  - name: HTTPS Check NET
    url: https://www.cloudflare.com
    timeout: 5s

  - name: ITCP Check GOOG
    url: tcp://8.8.8.8:53
    timeout: 5s

  - name: Portfolio
    url: https://www.hayechase.com
    timeout: 5s

  - name: Portfolio CI/CD
    url: gh-actions://chasehaye/portfolio_polished/main
    timeout: 5s

  - name: Fude-F
    url: https://www.fudesoftware.com
    timeout: 5s

  - name: Fude-F CI/CD
    url: gh-actions://chasehaye/fude_software_front/main
    timeout: 5s

  - name: Fude-B
    url: https://api.fudesoftware.com/api/status
    timeout: 5s

  - name: Fude-B CI/CD
    url: gh-actions://chasehaye/log_relay/main
    timeout: 5s

  - name: CdWx-F
    url: https://codewax.fyi
    timeout: 5s

  - name: CdWx-F CI/CD
    url: gh-actions://chasehaye/codewax-front/main
    timeout: 5s

  - name: CdWx-B
    url: https://api.codewax.fyi/api/status
    timeout: 5s

  - name: CdWx-B CI/CD
    url: gh-actions://chasehaye/codewax-back/main
    timeout: 5s
