interval: 5m

servers:
  - name: HTTPS Check NET
    url: https://www.cloudflare.com
    timeout: 3s

  - name: ITCP Check GOOG
    url: tcp://8.8.8.8:53
    timeout: 8s

  - name: Test 500
    url: https://httpstat.us/500
    timeout: 35s

  - name: Test 404
    url: https://httpstat.us/404
    timeout: 3s

  - name: Test CI Failure
    url: gh-actions://sindresorhus/got/refs/heads/repro-2444
    timeout: 10s
